#ifndef CLIME_HTTP_STATUS_H
#define CLIME_HTTP_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  LIME_HTTP_STATUS_CODE_INVALID                       = -1,

  LIME_HTTP_STATUS_CODE_CONTINUE                      = 100,
  LIME_HTTP_STATUS_CODE_SWITCHINGPROTOCOLS            = 101,
  LIME_HTTP_STATUS_CODE_PROCESSING                    = 102,
  LIME_HTTP_STATUS_CODE_EARLYHINTS                    = 103,

  LIME_HTTP_STATUS_CODE_OK                            = 200,
  LIME_HTTP_STATUS_CODE_CREATED                       = 201,
  LIME_HTTP_STATUS_CODE_ACCEPTED                      = 202,
  LIME_HTTP_STATUS_CODE_NONAUTHORITATIVEINFORMATION   = 203,
  LIME_HTTP_STATUS_CODE_NOCONTENT                     = 204,
  LIME_HTTP_STATUS_CODE_RESETCONTENT                  = 205,
  LIME_HTTP_STATUS_CODE_PARTIALCONTENT                = 206,
  LIME_HTTP_STATUS_CODE_MULTISTATUS                   = 207,
  LIME_HTTP_STATUS_CODE_ALREADYREPORTED               = 208,
  LIME_HTTP_STATUS_CODE_IMUSED                        = 226,

  LIME_HTTP_STATUS_CODE_MULTIPLECHOICES               = 300,
  LIME_HTTP_STATUS_CODE_MOVEDPERMANENTLY              = 301,
  LIME_HTTP_STATUS_CODE_FOUND                         = 302,
  LIME_HTTP_STATUS_CODE_SEEOTHER                      = 303,
  LIME_HTTP_STATUS_CODE_NOTMODIFIED                   = 304,
  LIME_HTTP_STATUS_CODE_USEPROXY                      = 305,
  LIME_HTTP_STATUS_CODE_TEMPORARYREDIRECT             = 307,
  LIME_HTTP_STATUS_CODE_PERMANENTREDIRECT             = 308,

  LIME_HTTP_STATUS_CODE_BADREQUEST                    = 400,
  LIME_HTTP_STATUS_CODE_UNAUTHORIZED                  = 401,
  LIME_HTTP_STATUS_CODE_PAYMENTREQUIRED               = 402,
  LIME_HTTP_STATUS_CODE_FORBIDDEN                     = 403,
  LIME_HTTP_STATUS_CODE_NOTFOUND                      = 404,
  LIME_HTTP_STATUS_CODE_METHODNOTALLOWED              = 405,
  LIME_HTTP_STATUS_CODE_NOTACCEPTABLE                 = 406,
  LIME_HTTP_STATUS_CODE_PROXYAUTHENTICATIONREQUIRED   = 407,
  LIME_HTTP_STATUS_CODE_REQUESTTIMEOUT                = 408,
  LIME_HTTP_STATUS_CODE_CONFLICT                      = 409,
  LIME_HTTP_STATUS_CODE_GONE                          = 410,
  LIME_HTTP_STATUS_CODE_LENGTHREQUIRED                = 411,
  LIME_HTTP_STATUS_CODE_PRECONDITIONFAILED            = 412,
  LIME_HTTP_STATUS_CODE_CONTENTTOOLARGE               = 413,
  LIME_HTTP_STATUS_CODE_PAYLOADTOOLARGE               = 413,
  LIME_HTTP_STATUS_CODE_URITOOLONG                    = 414,
  LIME_HTTP_STATUS_CODE_UNSUPPORTEDMEDIATYPE          = 415,
  LIME_HTTP_STATUS_CODE_RANGENOTSATISFIABLE           = 416,
  LIME_HTTP_STATUS_CODE_EXPECTATIONFAILED             = 417,
  LIME_HTTP_STATUS_CODE_IMATEAPOT                     = 418,
  LIME_HTTP_STATUS_CODE_MISDIRECTEDREQUEST            = 421,
  LIME_HTTP_STATUS_CODE_UNPROCESSABLECONTENT          = 422,
  LIME_HTTP_STATUS_CODE_UNPROCESSABLEENTITY           = 422,
  LIME_HTTP_STATUS_CODE_LOCKED                        = 423,
  LIME_HTTP_STATUS_CODE_FAILEDDEPENDENCY              = 424,
  LIME_HTTP_STATUS_CODE_TOOEARLY                      = 425,
  LIME_HTTP_STATUS_CODE_UPGRADEREQUIRED               = 426,
  LIME_HTTP_STATUS_CODE_PRECONDITIONREQUIRED          = 428,
  LIME_HTTP_STATUS_CODE_TOOMANYREQUESTS               = 429,
  LIME_HTTP_STATUS_CODE_REQUESTHEADERFIELDSTOOLARGE   = 431,
  LIME_HTTP_STATUS_CODE_UNAVAILABLEFORLEGALREASONS    = 451,

  LIME_HTTP_STATUS_CODE_INTERNALSERVERERROR           = 500,
  LIME_HTTP_STATUS_CODE_NOTIMPLEMENTED                = 501,
  LIME_HTTP_STATUS_CODE_BADGATEWAY                    = 502,
  LIME_HTTP_STATUS_CODE_SERVICEUNAVAILABLE            = 503,
  LIME_HTTP_STATUS_CODE_GATEWAYTIMEOUT                = 504,
  LIME_HTTP_STATUS_CODE_HTTPVERSIONNOTSUPPORTED       = 505,
  LIME_HTTP_STATUS_CODE_VARIANTALSONEGOTIATES         = 506,
  LIME_HTTP_STATUS_CODE_INSUFFICIENTSTORAGE           = 507,
  LIME_HTTP_STATUS_CODE_LOOPDETECTED                  = 508,
  LIME_HTTP_STATUS_CODE_NOTEXTENDED                   = 510,
  LIME_HTTP_STATUS_CODE_NETWORKAUTHENTICATIONREQUIRED = 511,
} LimeHttpStatusCode;

#ifdef __cplusplus
}
#endif

#endif
