/*
 * WARNING: This file is auto-generated by the 'version' script.
 * Any changes made manually will be lost the next time the code is generated.
 *
 * Please modify the source templates or generation logic instead.
 */

#ifndef LIME_VERSION_H
#define LIME_VERSION_H

#define VERSION_MAJOR 2
#define VERSION_MINOR 0
#define VERSION_PATCH 0
#define VERSION_EARLYRELEASE 4
#define VERSION_STR "2.0.0.4"

#endif // CLIME_VERSION_H
